### ISSUE TITLE
Unexpected Fault on Windows

### ISSUE THREAD

**Issue by cytek04** [cfstras/chromecsv#3]
Hi,
I recently downloaded the exe version of this for windows. When I try to run it, it throws a fatal error and ends. See below.

C:\Users\Cy\chromecsv>chromecsv.exe "%LOCALAPPDATA%\Google\Chrome\User Data"
Using C:\Users\Cy\AppData\Local\Google\Chrome\User Data/Default/Login Data
Loading database...
Columns found: origin_url, username_value, password_value,
Exporting stuff...
unexpected fault address 0x15d0000
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x15d0000 pc=0x424616]

goroutine 1 [running]:
runtime.throw(0x6930de)
        C:/Go/src/pkg/runtime/panic.c:464 +0x74 fp=0x15a2c90
runtime.sigpanic()
        C:/Go/src/pkg/runtime/os_windows.c:340 +0xfe fp=0x15a2ca8
runtime.memmove(0xc084037000, 0x15a2bc8, 0x6994c0)
        C:/Go/src/pkg/runtime/memmove_amd64.s:75 +0x76 fp=0x15a2cb0
runtime.gostringn(0x15a2d10, 0x15a2bc8, 0x6994c0)
        C:/Go/src/pkg/runtime/string.goc:79 +0x56 fp=0x15a2ce0
main._Cfunc_GoStringN(0x15a2bc8, 0xc0006994c0, 0xc084000100, 0x15a2bc8)
        C:/Users/Claus/AppData/Local/Temp/go-build284841727/_/C_/Users/Claus/vcs/chromecsv/_obj/_cgo_defun.c:18 +0x40 fp=0x15a2d00
main.(*WindowsCrypt).decrypt(0x6a01a8, 0xc0840340f0, 0x28, 0x28, 0x0, ...)
        C:/Users/Claus/vcs/chromecsv/crypt_windows.go:44 +0x70 fp=0x15a2d30
main.main()
        C:/Users/Claus/vcs/chromecsv/main.go:86 +0x9b9 fp=0x15a2f48
runtime.main()
        C:/Go/src/pkg/runtime/proc.c:220 +0x132 fp=0x15a2fa0
runtime.goexit()
        C:/Go/src/pkg/runtime/proc.c:1394 fp=0x15a2fa8

goroutine 3 [syscall]:
runtime.goexit()
        C:/Go/src/pkg/runtime/proc.c:1394

goroutine 4 [chan receive]:
database/sql.(*DB).connectionOpener(0xc08400d080)
        C:/Go/src/pkg/database/sql/sql.go:574 +0x41
created by database/sql.Open
        C:/Go/src/pkg/database/sql/sql.go:436 +0x250

I read the other issue on here and guessing maybe it is related to the same issue? Or is there something simple I am overlooking?

**Comment by cfstras** [comment]
Welp, I guess there's some error handling that's not being done. Looks like one of your passwords can't be decrypted and is throwing an error.

Since I don't have a windows system to debug this, you're on your own.

You could try:
1. checking the output of CryptUnprotectData in https://github.com/cfstras/chromecsv/blob/master/crypt_windows.go#L14 and returning null instead of something invalid
2. then using [GetLastError](https://golang.org/pkg/syscall/?GOOS=windows#GetLastError) to figure out what happened
3. skip the offending password.

PRs welcome ;)

**Comment by cfstras** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptunprotectdata might be helpful as well

**Comment by cytek04** [comment]
Thanks for the reply. Personally I do not think this is the issue because I have tried the exe on 3 different machines and it throws the same error. Also it was working and suddenly started throwing this error one day. I do not have enough time and programming experience to investigate much farther, though. It makes me wonder if it still works for others.

**Comment by eduardomarossi** [comment]
I have tried here, not working either on Windows x64, same fault.

**Comment by Zero3K** [comment]
It also doesn't work for me.
